package com.LuggageLogger.controller;

import com.LuggageLogger.model.Trip;
import com.LuggageLogger.repository.TripRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;

@CrossOrigin(origins = "http://localhost:4200")
@Controller 
@RequestMapping(path="/trips") 
public class TripController {
  @Autowired // This means to get the bean called tripRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private TripRepository tripRepository;


  @CrossOrigin
  @PostMapping(consumes={"application/json"}) // Map ONLY POST Requests
  public @ResponseBody String addNewTrip (@RequestBody Trip trip) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request


    tripRepository.save(trip);
    return "Saved";
  }

  @GetMapping
  public @ResponseBody Iterable<Trip> getAllTrips() {
    // This returns a JSON or XML with the trips
    return tripRepository.findAll();
  }
}
